[package]
name = "kosem-base-rpc-client"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[dependencies]
log = "0.4.11"
actix = "0.9.0"
awc = "1.0.1"
futures = "0.3.5"
actix-codec = "0.3.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"

kosem-webapi = { path = "../kosem-webapi" }
