[package]
name = "kosem-server"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[dependencies]
log = "0.4.8"
flexi_logger = "0.15.0"
actix-web = "2.0.0"
config = "0.10.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

futures = "0.3.4"
kosem-webapi = { path = "../kosem-webapi" }
actix = "0.9.0"
actix-web-actors = "2.0.0"
actix-rt = "1.0.0"
typed-builder = "0.5.1"
serde-value = "0.6.0"
