[package]
name = "kosem-server"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[dependencies]
log = "0.4.11"
flexi_logger = "0.15.11"
actix-web = "2.0.0"
config = "0.10.1"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"

futures = "0.3.5"
kosem-webapi = { path = "../kosem-webapi" }
actix = "0.9.0"
actix-web-actors = "2.0.0"
actix-rt = "1.1.1"
typed-builder = "0.7.0"
serde-value = "0.7.0"
