[package]
name = "kosem-server"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[dependencies]
log = "0.4.6"
flexi_logger = "0.11.4"
actix-web = "1.0.0"
config = "0.9.2"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"

kosem-webapi = { path = "../kosem-webapi" }
actix = "0.8.3"
actix-web-actors = "1.0.0"
