[package]
name = "kosem-webapi"
version = "0.1.0"
authors = ["Idan Arye <IdanArye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[lib]

[dependencies]
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
actix-web = "1.0.5"
actix = "0.8.3"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
serde-value = "0.6.0"
actix_derive = "0.5.0"
