[package]
name = "kosem-webapi"
version = "0.1.0"
authors = ["Idan Arye <IdanArye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[lib]

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
actix-web = "2.0.0"
actix = "0.9.0"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
serde-value = "0.7.0"
