[package]
name = "kosem-gui"
version = "0.1.0"
authors = ["IdanArye <idanarye@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/kosem"

[dependencies]
log = "0.4.7"
flexi_logger = "0.14.0"
config = "0.9.3"
serde = { version = "1.0.97", features = ["derive"] }
gtk = "0.7.0"
gio = ""
actix = "0.8.3"
awc = "0.2.2"
futures = "0.1.28"
actix-codec = "0.1.2"
typed-builder = "0.3.0"

kosem-webapi = { path = "../kosem-webapi" }
kosem-base-rpc-client = { path = "../kosem-base-rpc-client" }
